### ISSUE TITLE
Failed to Fetch Integrity (Everything correct)

### ISSUE THREAD

**Issue by FedeGioz** [Hazza3100/Twitch-account-creator#14]
Hi, when i start the program i get one message "[ x ] Failed to Fetch Integrity" per thread created. I had 6$ on capsolver and the proxies are WebShare, formatted with the tool. Every time i start the program my balance on CapSolver decreases by 5 cents. Can you fix it/help me? Thanks

**Comment by Hazza3100** [comment]
How many attempts have you done? Are you sure there user:pass@host:port format?
