### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by yomiyo17** [Hazza3100/Twitch-account-creator#15]
I keep getting a module not found error, could you help out please.

**Comment by Hazza3100** [comment]
Whatever the name is just do pip install moduleName

**Comment by yomiyo17** [comment]
Thank you, the only error now is it pulls a powershell page and just stays on the Threads: line without any update

**Comment by Hazza3100** [comment]
Print the exception

**Comment by yomiyo17** [comment]
thats another issue the exception doesn't it just shuts down the script, just a heads up i did not tweak with the code as i only have basic knowledge of python.

**Comment by yomiyo17** [comment]
I can message you on discord a Screenshot of the error

**Comment by Hazza3100** [comment]
Sure

**Comment by yomiyo17** [comment]
> Sure

Sent it to ya, dont know if you got it?

**Comment by Hazza3100** [comment]
Didn't receive anything.

**Comment by Hazza3100** [comment]
Could be a email issue

**Comment by yomiyo17** [comment]
> Could be a email issue

Like on my end? btw this is the error
![image](https://github.com/Hazza3100/Twitch-account-creator/assets/137181854/a4019a70-f60d-4a78-82f7-1e58d3bbbaeb)

**Comment by Hazza3100** [comment]
Either email or captcha error with response

**Comment by RetrosGUIs** [comment]
so u need captcha balance ?

**Comment by yomiyo17** [comment]
> so u need captcha balance ?

Yh i had a balance and that wasnt the issue, i never ended up solving it, but if u are also getting this we both might be doing something wrong lol

**Comment by Hazza3100** [comment]
I believe there is one issue I will resolve it very soon.

**Comment by yomiyo17** [comment]
> I believe there is one issue I will resolve it very soon.

No worries take your time. Thanks for being a good sport and actually working on it and responding.
