### ISSUE TITLE
Capsolver have removed the kasada task.

### ISSUE THREAD

**Issue by danokito** [Hazza3100/Twitch-account-creator#18]
Capsolver have removed the kasada task.

**Comment by danokito** [comment]
And that I can use kasada to replace my code?

**Comment by Hazza3100** [comment]
> And that I can use kasada to replace my code?

What?

**Comment by danokito** [comment]
If kasada doesn't work, I will need another tool to replace kasada, could you tell me which one should I use?

**Comment by Hazza3100** [comment]
> 
> 
> If kasada doesn't work, I will need another tool to replace kasada, could you tell me which one should I use?

Kasada task isn't a tool it's a service provided by capsolver, so you would either need an own solver or find another service.

**Comment by danokito** [comment]
And what service could replace kasada?

**Comment by Hazza3100** [comment]
> 
> 
> And what service could replace kasada?

It's not replacing kasada it would be replacing capsolver. I am unaware of any.
