### ISSUE TITLE
Invalid Kasada Link For Twitch

### ISSUE THREAD

**Issue by topji** [Hazza3100/Twitch-account-creator#6]
Just tried to use this script and after some debugging I can tell that the capsolver api is saying that the site is not supported, not quite sure what that is about but here is the response.
{'errorCode': 'ERROR_INVALID_TASK_DATA', 'errorDescription': 'unsupported site', 'errorId': 1}
When I get a little more time I will do some testing and if I get it fixed I will open a pull request but worth submitting an issue to bring it to your attention.

**Comment by topji** [comment]
Yeah, that is what I was thinking since it is no longer on the documentation page. Sucks, capsolver is cheap and it used to work well.

**Comment by Hazza3100** [comment]
Support responded they permanently removed it, so I don’t expect to see it again.
