### ISSUE TITLE
Failed to Fetch Integrity

### ISSUE THREAD

**Issue by Sppsupphack** [Hazza3100/Twitch-account-creator#8]
Failed to Fetch Integrity

https://passport.twitch.tv/integrity 404

**Comment by Hazza3100** [comment]
Have you added funds to your captcha api key?

**Comment by Sppsupphack** [comment]
uh no... But does it work if I add?

**Comment by Sppsupphack** [comment]
I now actually added some balance I got the same thing

[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity
[ x ] Failed to Fetch Integrity

**Comment by Sppsupphack** [comment]
so ye it doesnt work even if I have balance

**Comment by Hazza3100** [comment]
> so ye it doesnt work even if I have balance

It does, but your proxies probably don’t work. What format/provider are you using?

**Comment by Sppsupphack** [comment]
yee I use web thing u recomanded and yes I formated

**Comment by Hazza3100** [comment]
Contact me: Sandwich#9999

**Comment by Sppsupphack** [comment]
added
